import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../controller.dart';
import '../data.dart';
import '../models.dart';
import '../theme.dart';
import 'match_page.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final repo = DemoRepository();
  late final Future<List<MatchSummary>> _matches = repo.matches();
  bool live = false;
  final _url = TextEditingController(text: 'http://127.0.0.1:8000');

  @override
  void initState() {
    super.initState();
    // Deep link, e.g. ?match=mm-0004-comeback&seek=59&audience=analyst&lang=ur&club=IRN&play=1
    final q = Uri.base.queryParameters;
    final id = q['match'];
    if (id != null) {
      WidgetsBinding.instance.addPostFrameCallback((_) => _openId(id, q));
    }
  }

  void _openId(String id, Map<String, String> q) {
    final controller = MatchController.demo(matchId: id, repo: repo);
    controller.audience = Audience.values.firstWhere((a) => a.wire == q['audience'], orElse: () => Audience.fan);
    controller.language = Lang.values.firstWhere((l) => l.wire == q['lang'], orElse: () => Lang.en);
    controller.favouriteClubId = q['club'];
    controller.favouritePlayerId = q['player'];
    controller.openDrawerOnLoad = q['drawer'] == '1';
    controller.openRecapOnLoad = q['recap'] == '1';
    Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (_) => ChangeNotifierProvider(
          create: (_) => controller
            ..load().then((_) {
              final seek = double.tryParse(q['seek'] ?? '');
              if (seek != null) controller.seekTo(seek * 60000, showRecent: true);
              if (q['play'] == '1') controller.play();
            }),
          child: const MatchPage(),
        ),
      ),
    );
  }

  void _open(MatchSummary m) {
    final controller = live
        ? MatchController.live(matchId: m.matchId, repo: repo, baseUrl: _url.text.trim())
        : MatchController.demo(matchId: m.matchId, repo: repo);
    Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (_) => ChangeNotifierProvider(create: (_) => controller..load(), child: const MatchPage()),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final t = Theme.of(context).textTheme;
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 880),
            child: ListView(
              padding: const EdgeInsets.all(24),
              children: [
                Row(
                  children: [
                    const Icon(Icons.sports_soccer, color: MM.primary, size: 32),
                    const SizedBox(width: 12),
                    Text('MatchMind', style: t.headlineMedium?.copyWith(fontWeight: FontWeight.w800)),
                  ],
                ),
                const SizedBox(height: 8),
                Text(
                  'An AI broadcast booth: a team of agents turns live match events into stats, '
                  '"why it matters" insights, commentary and a recap, personalised for fans and analysts '
                  'in English, Urdu and Arabic.',
                  style: t.bodyLarge?.copyWith(color: MM.muted),
                ),
                const SizedBox(height: 24),
                _ModeCard(live: live, url: _url, onChanged: (v) => setState(() => live = v)),
                const SizedBox(height: 24),
                Text('Pick a match', style: t.titleMedium?.copyWith(fontWeight: FontWeight.w700)),
                const SizedBox(height: 12),
                FutureBuilder(
                  future: _matches,
                  builder: (context, snap) {
                    if (snap.hasError) return Text('Could not load matches: ${snap.error}');
                    if (!snap.hasData) return const LinearProgressIndicator();
                    return Column(
                      children: [
                        for (final m in snap.data!)
                          Padding(
                            padding: const EdgeInsets.only(bottom: 12),
                            child: _MatchTile(match: m, onTap: () => _open(m)),
                          ),
                      ],
                    );
                  },
                ),
                const SizedBox(height: 16),
                Text(
                  'All clubs, players and matches are fictional and generated by MatchMind.',
                  style: t.bodySmall?.copyWith(color: MM.muted),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _ModeCard extends StatelessWidget {
  const _ModeCard({required this.live, required this.url, required this.onChanged});

  final bool live;
  final TextEditingController url;
  final ValueChanged<bool> onChanged;

  @override
  Widget build(BuildContext context) {
    final t = Theme.of(context).textTheme;
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
              width: 360,
              child: SegmentedButton<bool>(
                showSelectedIcon: false,
                segments: const [
                  ButtonSegment(
                    value: false,
                    label: Text('Demo mode', softWrap: false),
                    icon: Icon(Icons.play_circle_outline),
                  ),
                  ButtonSegment(value: true, label: Text('Live agents', softWrap: false), icon: Icon(Icons.bolt)),
                ],
                selected: {live},
                onSelectionChanged: (s) => onChanged(s.first),
              ),
            ),
            const SizedBox(height: 12),
            Text(
              live
                  ? 'Connects to the MatchMind backend: the agent team runs while you watch, '
                        'personalised for your profile. Start it with: uv run uvicorn matchmind.api.app:app'
                  : 'Replays cards the agent team already produced. No backend, keys or quota needed.',
              style: t.bodyMedium?.copyWith(color: MM.muted),
            ),
            if (live) ...[
              const SizedBox(height: 12),
              TextField(
                controller: url,
                decoration: const InputDecoration(labelText: 'Backend URL', border: OutlineInputBorder()),
              ),
            ],
          ],
        ),
      ),
    );
  }
}

class _MatchTile extends StatelessWidget {
  const _MatchTile({required this.match, required this.onTap});

  final MatchSummary match;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final t = Theme.of(context).textTheme;
    return Card(
      child: InkWell(
        borderRadius: BorderRadius.circular(12),
        onTap: onTap,
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      match.title.toUpperCase(),
                      style: t.labelSmall?.copyWith(color: MM.highlight, letterSpacing: 1.2),
                    ),
                    const SizedBox(height: 6),
                    Text(
                      '${match.home}  v  ${match.away}',
                      style: t.titleMedium?.copyWith(fontWeight: FontWeight.w700),
                    ),
                    const SizedBox(height: 4),
                    Text(match.venue, style: t.bodySmall?.copyWith(color: MM.muted)),
                  ],
                ),
              ),
              const Icon(Icons.chevron_right, color: MM.primary),
            ],
          ),
        ),
      ),
    );
  }
}
