import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';

import '../controller.dart';
import '../models.dart';
import '../theme.dart';
import 'cards.dart';

class RecapPage extends StatelessWidget {
  const RecapPage({super.key});

  @override
  Widget build(BuildContext context) {
    final c = context.watch<MatchController>();
    final t = Theme.of(context).textTheme;
    final m = c.meta!;
    final card = c.recapCard;
    final recap = c.recap;
    final key = [
      for (final k in c.feed.reversed)
        if ((k.kind == 'goal' || k.kind == 'red_card') && k.type != 'commentary') k,
    ];
    final score = '${m.home.name} ${c.scoreHome}-${c.scoreAway} ${m.away.name}';

    String shareText() {
      final b = StringBuffer()
        ..writeln(card?.title ?? recap?.headline ?? 'Full time')
        ..writeln(score)
        ..writeln()
        ..writeln(card?.body ?? recap?.summary ?? '');
      if (recap != null) {
        b.writeln();
        for (final tp in recap.turningPoints) {
          b.writeln('- $tp');
        }
      }
      b
        ..writeln()
        ..writeln('Generated by MatchMind agents (fictional league)');
      return b.toString();
    }

    return Scaffold(
      appBar: AppBar(title: const Text('Full time')),
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 760),
          child: ListView(
            padding: const EdgeInsets.all(20),
            children: [
              Text(score, style: t.headlineSmall?.copyWith(fontWeight: FontWeight.w900)),
              Text(m.venue, style: t.bodySmall?.copyWith(color: MM.muted)),
              const SizedBox(height: 20),
              if (card != null)
                CardTile(card: card, lang: c.language, showSource: true)
              else if (recap != null)
                CardTile(
                  card: OverlayCard(
                    id: 'recap',
                    groupId: 'recap',
                    momentId: 'full_time',
                    matchMinute: 90,
                    period: 2,
                    displayAtMs: 0,
                    durationMs: 0,
                    type: 'recap',
                    audience: 'fan',
                    language: 'en',
                    title: recap.headline,
                    body: recap.summary,
                    importance: 1,
                    sourceAgent: 'narrator_agent',
                    fallbackUsed: false,
                    data: const {},
                  ),
                  lang: Lang.en,
                ),
              if (recap != null) ...[
                const SizedBox(height: 20),
                Text('TURNING POINTS', style: t.labelSmall?.copyWith(color: MM.muted, letterSpacing: 1.2)),
                const SizedBox(height: 8),
                for (final tp in recap.turningPoints)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 6),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Padding(
                          padding: EdgeInsets.only(top: 6),
                          child: Icon(Icons.circle, size: 8, color: MM.highlight),
                        ),
                        const SizedBox(width: 10),
                        Expanded(child: Text(tp, style: t.bodyMedium)),
                      ],
                    ),
                  ),
              ],
              if (key.isNotEmpty) ...[
                const SizedBox(height: 20),
                Text('KEY MOMENTS', style: t.labelSmall?.copyWith(color: MM.muted, letterSpacing: 1.2)),
                const SizedBox(height: 8),
                for (final k in key)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 8),
                    child: CardTile(card: k, lang: c.language, compact: true, minute: "${k.matchMinute + 1}'"),
                  ),
              ],
              const SizedBox(height: 20),
              FilledButton.icon(
                icon: const Icon(Icons.ios_share),
                label: const Text('Share recap as text'),
                onPressed: () async {
                  await Clipboard.setData(ClipboardData(text: shareText()));
                  if (context.mounted) {
                    ScaffoldMessenger.of(
                      context,
                    ).showSnackBar(const SnackBar(content: Text('Recap copied to clipboard')));
                  }
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
