"""Print the orchestrator's workflow graph as Mermaid, generated by Agent Framework's WorkflowViz.

Run from backend/:  uv run python scripts/workflow_diagram.py > ../docs/workflow.mmd
The diagram comes from the real workflow object, so the docs can't drift from the code.
"""

from __future__ import annotations

from agent_framework import WorkflowViz

from matchmind.agents.orchestrator import MatchOrchestrator
from matchmind.agents.stats_source import LocalStatsSource
from matchmind.generator import MATCHES_DIR
from matchmind.llm.gateway import LLMGateway
from matchmind.models import Match
from matchmind.state import MatchState


class _Unused:
    name = "unused"

    async def complete(self, *args, **kwargs):  # never called: we only draw the graph
        raise NotImplementedError


def main() -> None:
    match = Match.load(MATCHES_DIR / "mm-0004-comeback.json")
    state = MatchState(meta=match.meta)
    orch = MatchOrchestrator(state, LLMGateway([_Unused()]), LocalStatsSource(match.meta, []))
    print(WorkflowViz(orch.workflow).to_mermaid())


if __name__ == "__main__":
    main()
